### ISSUE TITLE
Проектирование датасетов

### ISSUE THREAD

**Issue by kwalag** [akimrx/yandex-tracker-exporter#6]
Привет! Спасибо за возможность использовать ваш экспортер. 

1. Не могли бы вы поделиться своей схемой/схемами датасетов, которые вы собираете?
Хочется использовать правильные соединения для грамотной визуализации данных. Или можно просто заджойнить иннером все таблицы как на скрине?
![image](https://github.com/akimrx/yandex-tracker-exporter/assets/46114122/ca1b2298-b6f4-40ed-ada3-f802858550a3)

2. Так и должно быть, что таблицы issues_changelog, issues_changelog_view - пустые и их не нужно использовать?

3. Не понял по коду, что считается за busdays_duration?

4. Верно что за длительность выполнения задачи берется итоговый human_readable_duration? Или лучше спрошу так, как в итоге выводить дни? Какой атрибут за это отвечает, или нужна какая-то формула?

Если вдруг можно с кем-то связаться для доп. вопросов в телеграме, буду благодарен!

**Comment by akimrx** [comment]
Привет!

1. На недавнем Datalens Fest я подготавливал демо-дашборд, его можно задеплоить в ваш Datalens здесь: https://datalens.yandex.ru/marketplace/f2ejcgrg2h910r7cc93u
Там же можно посмотреть как устроены джойны таблиц

2. По-умолчанию экспорт changelog отключен, т.к. он замедляет экспорт метрик за итерацию, но его можно включить переменной окружения `EXPORTER_CHANGELOG_EXPORT_ENABLED=true` , все переменные [доступны здесь](https://github.com/akimrx/yandex-tracker-exporter?tab=readme-ov-file#general-settings)

3. Время нахождения в статусах только в рабочие часы. По умолчанию это с 9:00 до 22:00, не считая выходные и праздники РФ. Управлять рабочими часами можно через переменные окружения `EXPORTER_BUSINESS_HOURS_START` и `EXPORTER_BUSINESS_HOURS_END`. Подробнее [здесь]( https://github.com/akimrx/yandex-tracker-exporter?tab=readme-ov-file#general-settings)

4. human_readable_duration — это просто строка, мы ее используем для удобства в отчетах. По сути это просто конвертированная duration в человекочитаемый строковый формат. Для графиков/диаграмм нужно использовать либо `duration`, либо `busday_duration`, в зависимости от того, что хотите считать — общее время или только рабочее

По доп. вопросам можно писать мне в телеграм — `@akimrx`

![image](https://github.com/akimrx/yandex-tracker-exporter/assets/44138907/d598ed1e-8265-4dbf-8bc3-fe455d412e3d)
