### ISSUE TITLE
Подсчет количества SP в Datalens

### ISSUE THREAD

**Issue by kwalag** [akimrx/yandex-tracker-exporter#7]
Добрый день!

Строю чарты с использованием агрегата по SP, и понимаю что есть какая-то проблема. 

**Пример 1:** 
Я вывел все очереди, и по ним посчиталась одна сумма SP
![Screenshot at Jan 12 17-42-15](https://github.com/akimrx/yandex-tracker-exporter/assets/46114122/a426f72f-11a5-4cfa-8830-15e1f907326c)

Затем я сбросил выбор, и по логике должно появится то же число SP, но оно меняется
![Screenshot at Jan 12 17-42-28](https://github.com/akimrx/yandex-tracker-exporter/assets/46114122/dff2e571-ee93-411c-9516-2ea4607e0533)

Параметров больше никаких не выбрано. 

**Пример 2:** 
Выбрал пару значений, и показалось такое количество SP по параметру story_points(1)
![image](https://github.com/akimrx/yandex-tracker-exporter/assets/46114122/ce5db78d-8beb-4c78-a602-f365cc63eb36)

Поменял чарт на параметр story_points и количество поменялось
![image](https://github.com/akimrx/yandex-tracker-exporter/assets/46114122/f0e5416a-aa67-497b-8a5c-e41e121fa578)

При этом, ни то, ни другое значение - неверно. Сумма должна быть равна 77SP, вот выборка неизменяющаяся:
![image](https://github.com/akimrx/yandex-tracker-exporter/assets/46114122/d695c0eb-4756-47b9-901c-dd6d4cae2c80)

Приложу на всякий случай настройки чарта, они дефолтные, агрегат по сумме. 
![image](https://github.com/akimrx/yandex-tracker-exporter/assets/46114122/78120577-1e41-49d6-8237-0546c02ae107)

**Comment by akimrx** [comment]
Привет! С подсчетом SP в Datalens есть особенность, в частности она возникает из-за того, что при JOIN данных могут быть дубликаты из-за обилия статусов в метриках, поэтому нужно немного править датасет, создавая поле для рассчета суммы SP.

На Datalens Fest 2023 я публиковал демо-дашборд, который можно посмотреть здесь — https://datalens.yandex.ru/marketplace/f2ejcgrg2h910r7cc93u, там есть вариант решения этой проблемы.

Если кратко, то нужно поле в датасете с функцией `SUM([story_points] BEFORE FILTER BY [status_name])`, его и использовать в рассчете

В некоторых случаях может подойти `SUM([story_points] FIXED [status_name], [status])`

![image](https://github.com/akimrx/yandex-tracker-exporter/assets/44138907/b4047e74-1515-404a-be8c-9f69c2e27ed5)
