### ISSUE TITLE
Нет спринтов

### ISSUE THREAD

**Issue by kwalag** [akimrx/yandex-tracker-exporter#8]
Во вкладке Issues дэшборда YCLIENTS R&D вы выводите спринты, но такого атрибута в базе кажется нет (не могу найти).

В коде вы также отмечаете, что фильтровать по спринтам не получится. Не могу в итоге понять, их можно как-то выводить, или нет?
<img width="804" alt="image" src="https://github.com/akimrx/yandex-tracker-exporter/assets/46114122/2612df3b-caa2-49e1-b122-f9d1d0feda8c">

**Comment by kwalag** [comment]
upd нашел))

**Comment by akimrx** [comment]
Привет! Спринты есть в стандартном наборе полей. А на скрине это обработчик действительно странных артефактов в трекере, когда связь со спринтом есть, а сущность по API отдает 404)
